export const featureData = [
  { title: 'Revenue', money: '$4,215', moneyRate: '+13.4' },
  { title: 'Sales', money: '$5,915', moneyRate: '+9.4' },
  { title: 'Cost', money: '$2,225', moneyRate: '+8.4' },
];

export const userData = [
  { name: 'Jan', 'Active User': 4000 },
  { name: 'Fev', 'Active User': 3000 },
  { name: 'Mar', 'Active User': 3000 },
  { name: 'Abr', 'Active User': 2780 },
  { name: 'Mai', 'Active User': 1890 },
  { name: 'Jun', 'Active User': 2390 },
  { name: 'Jul', 'Active User': 3490 },
  { name: 'Ago', 'Active User': 2490 },
  { name: 'Set', 'Active User': 3460 },
  { name: 'Out', 'Active User': 4490 },
  { name: 'Nov', 'Active User': 5000 },
  { name: 'Dez', 'Active User': 2500 },
];

export const newMemberRows = [
  {
    id: 1,
    username: 'Mary Jane',
    avatar: 'https://github.com/MiguelDuqueFilho.png',
    occupation: 'Software Engineer',
  },
  {
    id: 2,
    username: 'Lovely Singh',
    avatar: 'https://github.com/MiguelDuqueFilho.png',
    occupation: 'Software Architect',
  },
  {
    id: 3,
    username: 'Shikha Das',
    avatar: 'https://github.com/MiguelDuqueFilho.png',
    occupation: 'Senior Designer',
  },
  {
    id: 4,
    username: 'Reema Jain',
    avatar: 'https://github.com/MiguelDuqueFilho.png',
    occupation: 'Senior Manager',
  },
  {
    id: 5,
    username: 'Robin Hood',
    avatar: 'https://github.com/MiguelDuqueFilho.png',
    occupation: 'Product Manager',
  },
];

export const lastTransctionRows = [
  {
    id: 1,
    username: 'John Traversy',
    avatar: 'https://github.com/MiguelDuqueFilho.png',
    date: '2 Jun 2021',
    type: 'Approved',
    bgColor: '#e5faf2',
    fdColor: '#3bb077',
    transaction: '$420.00',
  },
  {
    id: 2,
    username: 'Parag Khandar',
    avatar: 'https://github.com/MiguelDuqueFilho.png',
    date: '2 Jul 2021',
    type: 'Declined',
    bgColor: '#fff0f1',
    fdColor: '#d95087',
    transaction: '$320.00',
  },
  {
    id: 3,
    username: 'Saira Hussian',
    avatar: 'https://github.com/MiguelDuqueFilho.png',
    date: '25 Aug 2021',
    type: 'Approved',
    bgColor: '#e5faf2',
    fdColor: '#3bb077',
    transaction: '$720.00',
  },
  {
    id: 4,
    username: 'Rohit Malik',
    avatar: 'https://github.com/MiguelDuqueFilho.png',
    date: '5 Jun 2021',
    type: 'Pending',
    transaction: '$720.00',
  },
];

export const userRows = [
  {
    id: 1,
    username: 'Mary Jane',
    avatar: 'https://randomuser.me/api/portraits/women/1.jpg',
    email: 'mary@gmail.com',
    status: 'active',
    transaction: '$180.00',
  },
  {
    id: 2,
    username: 'Lovely Singh',
    avatar: 'https://randomuser.me/api/portraits/women/10.jpg',
    email: 'lovely@gmail.com',
    status: 'active',
    transaction: '$220.00',
  },
  {
    id: 3,
    username: 'Shikha Das',
    avatar: 'https://randomuser.me/api/portraits/women/15.jpg',
    email: 'shikha@gmail.com',
    status: 'active',
    transaction: '$320.00',
  },
  {
    id: 4,
    username: 'Reema Jain',
    avatar: 'https://randomuser.me/api/portraits/women/34.jpg',
    email: 'reema@gmail.com',
    status: 'active',
    transaction: '$110.00',
  },
  {
    id: 5,
    username: 'Robin Hood',
    avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    email: 'robin@gmail.com',
    status: 'active',
    transaction: '$120.00',
  },
  {
    id: 6,
    username: 'Aamir Jain',
    avatar: 'https://randomuser.me/api/portraits/men/12.jpg',
    email: 'aamir@gmail.com',
    status: 'active',
    transaction: '$220.00',
  },
  {
    id: 7,
    username: 'John Traversy',
    avatar: 'https://randomuser.me/api/portraits/men/18.jpg',
    email: 'john@gmail.com',
    status: 'active',
    transaction: '$420.00',
  },
  {
    id: 8,
    username: 'Parag Khandar',
    avatar: 'https://randomuser.me/api/portraits/men/22.jpg',
    email: 'parag@gmail.com',
    status: 'active',
    transaction: '$320.00',
  },
  {
    id: 9,
    username: 'Saira Hussian',
    avatar: 'https://randomuser.me/api/portraits/women/77.jpg',
    email: 'saira@gmail.com',
    status: 'active',
    transaction: '$720.00',
  },
  {
    id: 10,
    username: 'Rohit Malik',
    avatar: 'https://randomuser.me/api/portraits/men/28.jpg',
    email: 'rohit@gmail.com',
    status: 'active',
    transaction: '$720.00',
  },
];
